const productsData = [
    { id: 1, name: "Kit Básico Azul", cat: "kit", price: 16.00, desc: "Incluye: Tensiómetro manual + estetoscopio de una campana + bolsito.", img: "img/kit-basico-azul.png", gallery: ["img/tensiometro-azul.png", "img/estetoscopio-azul.png", "img/bolsito-azul.png"], 
    { id: 2, name: "Kit Color Gris", cat: "kit", price: 20.00, desc: "Incluye: Tensiómetro manual + estetoscopio doble campana + bolsito.", img: "img/kit-color-gris.png" },
    { id: 3, name: "Kit Deluxe", cat: "kit", price: 35.00, desc: "Colores: Fucsia, Negro, Azul, Celeste y Conchovino.\nIncluye: Tensiómetro manual + estetoscopio doble campana + bolsito. Gratis linterna.", img: "img/kit-deluxe.png" },
    { id: 4, name: "Kit de diagnostico", cat: "kit", price: 34.75, desc: "Colores: Rosado, negro, púrpura.\nIncluye: Tensiometro manual + estetoscopio Pro + torniquete elástico + tijera corta todo + Bolsito", img: "img/kit-diagnostico.png" },
    { id: 5, name: "Kit Profesional", cat: "kit", price: 75.00, desc: "Colores: Negro, Rosado, Morado.\nIncluye: Bolsito + estetoscopio clínico profesional + Tensiometro manual + reloj segundero + tijera corta todo + repuestos para estetoscopio + linterna de Examinacion.", img: "img/kit-profesional.png" },
    { id: 6, name: "Kit Completo / Safe Medic", cat: "kit", price: 49.00, desc: "Colores: púrpura, fucsia y negro.\nIncluye: Tensiometro manual, Estetoscopio doble campana, termómetro digital, torniquete, tijera corta todo, Bolsito.\nObsequio: linterna de Examinacion y esfero", img: "img/kit-completo-safe-medic.png" },
    { id: 7, name: "Kit médico con Estuche", cat: "kit", price: 46.50, desc: "Incluye: Bolsito + estetoscopio pro + Tensiometro manual + estuche para estetoscopio.\nColores del kit: fucsia, negro, celeste, azul, conchovino\nPúrpura agotado\nPregúntanos por internos los colores disponibles de los estuches.", img: "img/kit-medico-estuche.png" },
    { id: 8, name: "Combito Diatest #2", cat: "kit", price: 41.00, desc: "Incluye: Glucometro + 10 tiras reactivas + 10 lancetas + lancetero + estuche + líquidos activos para la máquina + rompe ampolla.\nAdicional:\n50 tiras reactivas\n100 lancetas", img: "img/diatest-2.png" },
    { id: 9, name: "Combito Diatest #3", cat: "kit", price: 38.75, desc: "Incluye: Glucometro + 10 tiras reactivas + 10 lancetas + lancetero + estuche + líquidos activos para la máquina + termómetro digital.\nAdicional:\n50 tiras reactivas\n100 lancetas", img: "img/diatest-3.png" },
    { id: 10, name: "Combito Diatest #4", cat: "kit", price: 55.00, desc: "Incluye: Glucometro + 10 tiras reactivas + 10 lancetas + lancetero + estuche + líquidos activos para la máquina + Oximetro Estándar.\nAdicional:\n50 tiras reactivas\n100 lancetas", img: "img/diatest-4.png" },
    { id: 11, name: "Combito Diatest #5", cat: "kit", price: 43.00, desc: "Incluye: Glucometro + 10 tiras reactivas + 10 lancetas + lancetero + estuche + líquidos activos para la máquina + reloj segundero.\nAdicional:\n50 tiras reactivas\n100 lancetas", img: "img/diatest-5.png" },
    { id: 12, name: "Kit Médico Pro", cat: "kit", price: 26.75, desc: "Incluye: Bolsito, Tensiometro manual, estetoscopio doble campana pro.\nColores: Negro, rosa, púrpura", img: "img/kit-medico-pro.png" },
    { id: 13, name: "Kit Completo de enfermería #1", cat: "kit", price: 84.00, desc: "Inluye: Tensiometro manual + estetoscopio de una campana + gorrito quirurgico + rompe ampolla + torniquete + Oximetro + reloj segundero + termómetro digital + Bolsito.\nObsequio: 1 Pluma\nNo incluye pines para estetoscopio\nColor: azul marino", img: "img/kit-completo-enfermeria-1.png" },
    { id: 14, name: "Kit Completo de enfermería #2", cat: "kit", price: 64.75, desc: "Incluye: Tensiometro manual + Estetoscopio doble campana + termómetro digital + Oximetro + reloj segundero + Bolsito.\nObsequio: 1 Pluma\nNo incluye pines para estetoscopio", img: "img/kit-completo-enfermeria-2.png" },
    { id: 15, name: "Set de organizador #1", cat: "accesorios", price: 21.50, desc: "Incluye: Organizador de bolsillo + tijera corta todo + Rompe ampolla.", img: "img/set-organizador-1.png" },
    { id: 16, name: "Set de organizador #2", cat: "accesorios", price: 18.00, desc: "Incluye: Organizador de bolsillo + dispensador de gel 1oz + rompe ampolla", img: "img/set-organizador-2.png" },
    { id: 17, name: "Reloj para bolsillo", cat: "accesorios", price: 10.00, desc: "Reloj enfermera de solapa tipo broche.", img: "img/reloj-para-bolsillo.png" },
    { id: 18, name: "Dispensador de gel 1 oz", cat: "accesorios", price: 2.00, desc: "Dispensador de gel desinfectante de 1 oz.", img: "img/dispensador-de-alcohol-1oz.png" },
    { id: 19, name: "Porta credencial con collar", cat: "accesorios", price: 3.80, desc: "Porta credencial con collar y diseños variados.", img: "img/porta-credenciales-para-bolsillo.png" },
    { id: 20, name: "Bolso Paramedico", cat: "accesorios", price: 20.00, desc: "Colores: Gris y rojo", img: "img/bolso-paramedico.png" },
    { id: 21, name: "Gorritos quirúrgicos con botón", cat: "accesorios", price: 6.00, desc: "", img: "img/gorrito-con-boton.png" },
    { id: 22, name: "Gorro quirúrgico Jorge el curioso", cat: "accesorios", price: 4.75, desc: "", img: "img/gorro-quirurgico-mono.png" },
    { id: 23, name: "Cinta Metrica", cat: "accesorios", price: 4.00, desc: "Con diseño de flores", img: "img/cinta-metrica-con-diseño-de-flores.png" },
    { id: 24, name: "Dispensador de gel 1 oz con llavero", cat: "accesorios", price: 2.50, desc: "Colores: Rosa, celeste y verde", img: "img/dispensador-de-alcohol-1oz-con-llavero.png" },
    { id: 25, name: "Dispensador de alcohol mediano", cat: "accesorios", price: 4.40, desc: "", img: "img/dispensadores-de-alcohol-medianos.png" },
    { id: 26, name: "Dispensador de alcohol mini", cat: "accesorios", price: 3.75, desc: "Varios colores", img: "img/dispensador-alcohol-mini.png" },
    { id: 27, name: "Dispensador de gel 1oz Con llavero de flor", cat: "accesorios", price: 2.75, desc: "", img: "img/dispensador-llavero.png" },
    { id: 28, name: "Layard médicos", cat: "accesorios", price: 2.75, desc: "Varios modelos", img: "img/layard-medicos.png" },
    { id: 29, name: "Mini calculadora", cat: "accesorios", price: 3.50, desc: "Colores: Rosa, azul y púrpura", img: "img/mini-calculadoras.png" },
    { id: 30, name: "Mini dispensador de lazos", cat: "accesorios", price: 4.75, desc: "", img: "img/mini-dispensador-de-lazos.png" },
    { id: 31, name: "Termometro de Mercurio", cat: "accesorios", price: 3.75, desc: "", img: "img/termometro-mercurio.png" },
    { id: 32, name: "Termómetro digital con diseño de vaquita", cat: "accesorios", price: 4.00, desc: "Disponible en color rosado", img: "img/termometro-vaquita.png" },
    { id: 33, name: "Pines para estetoscopio", cat: "accesorios", price: 1.00, desc: "Varios diseños disponibles", img: "img/pines-para-estetoscopio.png" },
    { id: 34, name: "Pines médicos con diseño de Osito", cat: "accesorios", price: 2.75, desc: "Diseño de esmalte", img: "img/pines-medico-osito.png" },
    { id: 35, name: "Pines Médicos con broche", cat: "accesorios", price: 2.50, desc: "Con diseño de animales medicos", img: "img/pines-medicos-broche.png" },
    { id: 36, name: "Pines de lazos de plástico", cat: "accesorios", price: 2.50, desc: "", img: "img/pines-lazos-plastico.png" },
    { id: 37, name: "Estuche para Estetoscopio", cat: "accesorios", price: 13.50, desc: "Estuche de almacenamiento para tu kit manual o estetoscopio\nColores: lila y rosa", img: "img/estuche-estestocopio.png" },
    { id: 38, name: "Cartucheras para enfermería", cat: "accesorios", price: 3.50, desc: "", img: "img/cartuchera-enfermera.png" },
    { id: 39, name: "Tablero de Plastico", cat: "prácticas", price: 6.75, desc: "Colores: Rosa, Verde menta, Celeste", img: "img/tablero-plastico.png" },
    { id: 40, name: "Estetoscopio Clínico Profesional", cat: "equipo medico", price: 68.00, desc: "Accesorios: repuestos olivas y repuesto de campana.\nPor la compra de tu estetoscopio profesional, lleva gratis un estuche para estetoscopio", img: "img/estetoscopio-clinico.png" },
    { id: 41, name: "Estetoscopio pediatrico", cat: "equipos medicos", price: 38.50, desc: "Accesorios combinables de figuras\nColores: púrpura, amarillo, celeste", img: "img/estetoscopio-pedriatico.png" },
    { id: 42, name: "Caja Organizadora Pequeña", cat: "equipos medicos", price: 6.50, desc: "Material de Plastico", img: "img/caja-organizadora-pequeña.png" },
    { id: 43, name: "Otoscopio profesional", cat: "equipos medicos", price: 55.00, desc: "Incluye: Otoscopio, pilas, repuestos y estuche de tela", img: "img/otoscopio-profesional.png" }
];
